---
- name: Vérification de l'installation de rsyslog-gnutls
  command: rsyslogd -v
  register: rsyslog_version
  changed_when: false

- name: Afficher la version de rsyslog
  debug:
    msg: "Version de rsyslog : {{ rsyslog_version.stdout }}"

- name: Créer le répertoire pour les certificats SSL de RSyslog
  file:
    path: /etc/ssl/rsyslog
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copier le certificat CA sur le client
  copy:
    src: "{{ ssl_cert_path }}/server.crt"
    dest: /etc/ssl/rsyslog/server.crt
    owner: root
    group: root
    mode: '0644'

- name: Configurer RSyslog pour envoyer les logs au serveur central
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    mode: '0644'


