all:
  hosts:
    rsyslog_server:
      ansible_host: 127.0.0.1  # Adresse locale si Ansible et le serveur sont sur la même machine
      ansible_user: user  # Remplacez par votre utilisateur local
      ansible_connection: local  # Connexion locale au lieu de SSH

    client1:
      ansible_host: 192.168.198.136
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_become: true

      
      
    client2:
      ansible_host: 192.168.198.137
      ansible_user: client
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_become: true

      
      
   
