---
- name: Mise à jour du système
  apt:
    update_cache: yes
    upgrade: yes

- name: Installation de UFW (si pas déjà installé)
  apt:
    name: ufw
    state: present

- name: Autoriser le trafic entrant pour Rsyslog sur le port 6514 (TCP)
  ufw:
    rule: allow
    port: 6514
    proto: tcp

- name: Autoriser SSH (port 22)
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Activation du pare-feu UFW
  ufw:
    state: enabled
    policy: allow  # Ou "deny" si nécessaire


- name: Installation des paquets nécessaires pour Rsyslog sur le serveur
  apt:
    name:
      - rsyslog
      - rsyslog-gnutls
      - ufw
    state: present
    update_cache: yes

- name: Installation de GnuTLS pour les connexions sécurisées
  apt:
    name: gnutls-bin
    state: present

- name: Vérification de l'installation de rsyslog-gnutls
  command: rsyslogd -v
  register: rsyslog_version
  changed_when: false
